services:

  frontend:
    image: ghcr.io/liquidai-project/energy-demo-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - ${FRONTEND_PORT-5173}:5173
    environment:
      ANIMATION_MOVING_TIME: ${ANIMATION_MOVING_TIME}

volumes:
  mongo-config:
  mongo-db:


networks:
  default:
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24
